### ISSUE TITLE
User Story: Som bruger vil jeg kunne søge efter varer, så jeg hurtigt kan finde noget bestemt til min ønskeliste.

### ISSUE THREAD

**Issue by ajoeili** [ajoeili/WishList#11]
**Acceptance criteria:**

[ ] Brugeren kan indtaste søgeord i søgefeltet og få en liste af varer, der matcher.
[ ] Søgning returnerer varer med billede, pris, forhandler, tags og mulighed for tilføjelse til ønskeliste.
[ ] Brugeren får besked, hvis ingen varer matcher søgningen.

**Tasks:** 

- [ ] Implementer backend API til søgning i varedata.
- [ ] Design frontend UI til søgefelt og visning af søgeresultater.
- [ ] Test søgefunktionaliteten og feedback, hvis ingen varer matcher søgningen.
- [ ] Test visningen af søgeresultater (varer med billede, pris, forhandler og tags).
