### ISSUE TITLE
CI/CD og GitHub Actions

### ISSUE THREAD

**Issue by ajoeili** [ajoeili/WishList#15]
**Tasks:** 

- [x] Opsæt GitHub repository og tilføj filer.
- [x] Implementér workflow til automatiseret build og test for feature-branches og pull requests.
- [ ] Opsæt CD-pipeline til at deploye applikationen til Azure PaaS.
- [ ] Dokumentér CI/CD-processen og opsætning i README.
