### ISSUE TITLE
Dokumentation og modeller

### ISSUE THREAD

**Issue by ajoeili** [ajoeili/WishList#2]
**Tasks:**

- [ ] Udarbejd ER-diagram for database.
- [ ] Opret klassediagram for projektet.
- [ ] Udfør risikoanalyse med fokus på mitigerende handlinger.
- [ ] Udfør interessentanalyse med identifikation og håndtering af interessenter.
- [ ] Udarbejd dokument om bæredygtighed og dataetik, som specificeret i projektbeskrivelsen.
