### ISSUE TITLE
User Story: Som bruger vil jeg kunne se hele min ønskeliste, så jeg har overblik over alle de varer, jeg ønsker.

### ISSUE THREAD

**Issue by ajoeili** [ajoeili/WishList#6]
**Acceptance criteria:**

[ ] Brugeren kan åbne sin ønskeliste fra menuen.
[ ] Ønskelisten viser alle varer med billede, pris, forhandlerlink, tags og mulighed for at slette varen.
[ ] Ønskelisten opdateres dynamisk, hvis der tilføjes eller fjernes varer.

**Tasks:**

- [ ] Implementer backend API til at hente varer fra ønskelisten.
- [ ] Design og implementer frontend UI til visning af ønskelisten (vis billeder, pris, forhandler og tags).
- [ ] Tilføj dynamisk opdatering, så listen ændres ved tilføjelse/sletning af varer.
- [ ] Test visning af ønskeliste og tjek for korrekte data.
